#!/usr/bin/env bash

host=$(hostname -f)

while getopts "h:" flag; do
 case $flag in
   h)
   host=$OPTARG
   ;;
 esac
done

# echo $host

sudo nixos-rebuild switch --flake .#$host

# TODO Push to git branch when deploying
# https://medium.com/@wujido20/handling-flags-in-bash-scripts-4b06b4d0ed04
