#!/usr/bin/env bash

scp -r ./secrets/bishop/ nixos-103-bishop:~/secrets
# scp -r ./secrets/bishop/ nixos-104-bishop:~/secrets
# scp -r ./secrets/bishop/ nixos-105-bishop:~/secrets
# scp -r ./secrets/bishop/ nixos-200-bishop:~/secrets

ssh nixos-103-bishop "sudo rm -r /run/secrets/* && sudo mv ~/secrets/bishop/* /run/secrets && sudo chown -R vault /run/secrets"
# ssh nixos-104-bishop "sudo rm -r /run/secrets/* && sudo mv ~/secrets/bishop/* /run/secrets && sudo chown -R vault /run/secrets"
# ssh nixos-105-bishop "sudo rm -r /run/secrets/* && sudo mv ~/secrets/bishop/* /run/secrets && sudo chown -R vault /run/secrets"
# ssh nixos-200-bishop "sudo rm -r /run/secrets/* && sudo mv ~/secrets/bishop/* /run/secrets && sudo chown -R vault /run/secrets"
