on:
  push:
jobs:
  get-hosts:
    runs-on: ubuntu-22.04
    outputs:
      hosts: ${{ steps.hosts.outputs.hosts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Show flake hosts
        id: hosts
        run: |
          nix flake show --json > /tmp/configurations.json
          jq -r '.nixosConfigurations | keys | @json' /tmp/configurations.json > /tmp/hosts.json
          echo "hosts=$(cat /tmp/hosts.json)" >> $GITHUB_OUTPUT

  build-host:
    needs: get-hosts
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      matrix:
        host: ${{ fromJSON(needs.get-hosts.outputs.hosts) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      # yoinked from https://github.com/ashhhleyyy/forest/blob/main/.github/workflows/cache.yml
      - name: Remove unneccessary packages
        run: 'echo "=== Before pruning ==="

          df -h

          sudo rm -rf /usr/bin/buildah /usr/bin/containerd* /usr/bin/ctr /usr/bin/docker*
          /usr/bin/gh /usr/bin/git /usr/bin/gpg /usr/bin/grub* /usr/bin/mono-sgen
          /usr/bin/myisam* /usr/bin/mysql* /usr/bin/openssl /usr/bin/pedump /usr/bin/php*
          /usr/bin/podman /usr/bin/python3.10 /usr/bin/shellcheck /usr/bin/skopeo
          /usr/bin/snap /usr/bin/tcpdump /usr/bin/tmux /usr/bin/x86_64-linux-gnu-*
          /usr/bin/yq /opt /usr/local /usr/share /var/lib /var/log || true

          echo

          echo "=== After pruning ==="

          df -h
          '

      - name: Build host
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
